# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-11-15 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinfo',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
