# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-11-16 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_typeinfo_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gadv',
            field=models.BooleanField(default=False),
        ),
    ]
