# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-11-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uemail',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
